//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UspsAddressApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UspsAddressApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPSCOM::DoAuth.
        /// </summary>
        internal static string AuthorizationValue {
            get {
                return ResourceManager.GetString("AuthorizationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityElementName {
            get {
                return ResourceManager.GetString("CityElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionElementName {
            get {
                return ResourceManager.GetString("DescriptionElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsn_brd_eagle_302x134 {
            get {
                object obj = ResourceManager.GetObject("dsn_brd_eagle_302x134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_find {
            get {
                object obj = ResourceManager.GetObject("edit_find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorElementName {
            get {
                return ResourceManager.GetString("ErrorElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserID. Check Environment Variable UspsUserID..
        /// </summary>
        internal static string InvalidUserIDMessage {
            get {
                return ResourceManager.GetString("InvalidUserIDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityStateLookupRequest.
        /// </summary>
        internal static string RequestElementName {
            get {
                return ResourceManager.GetString("RequestElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityStateLookupResponse.
        /// </summary>
        internal static string ResponseElementName {
            get {
                return ResourceManager.GetString("ResponseElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SourceElementName {
            get {
                return ResourceManager.GetString("SourceElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateElementName {
            get {
                return ResourceManager.GetString("StateElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.  Save input and contact the developer.
        /// </summary>
        internal static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERID.
        /// </summary>
        internal static string UserIDAttribute {
            get {
                return ResourceManager.GetString("UserIDAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip5.
        /// </summary>
        internal static string Zip5ElementName {
            get {
                return ResourceManager.GetString("Zip5ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code must be 5 numeric characters.
        /// </summary>
        internal static string ZipCode5NumericErrorMessage {
            get {
                return ResourceManager.GetString("ZipCode5NumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        internal static string ZipCodeElementName {
            get {
                return ResourceManager.GetString("ZipCodeElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ZipCodeIDAttribute {
            get {
                return ResourceManager.GetString("ZipCodeIDAttribute", resourceCulture);
            }
        }
    }
}
